### ISSUE TITLE
issue patch 11.6 

### ISSUE THREAD

**Issue by magnifico1966** [RehabMan/patch-nvme#1]
Hello rehab , where i wrong ? please 
Last login: Tue Jul 19 13:25:12 on ttys001
Airdimagnifico:~ magnifico$ cd /Users/magnifico/Desktop/patch_nvme 
Airdimagnifico:patch_nvme magnifico$ /Users/magnifico/Desktop/patch_nvme/NVMe_patches_10_11_6.plist 
/Users/magnifico/Desktop/patch_nvme/NVMe_patches_10_11_6.plist: line 1: syntax error near unexpected token `newline'
/Users/magnifico/Desktop/patch_nvme/NVMe_patches_10_11_6.plist: line 1:`<?xml version="1.0" encoding="UTF-8"?>'
Airdimagnifico:patch_nvme magnifico$

**Comment by RehabMan** [comment]
It seems where you went wrong is not reading the README.
A plist is not something executable in Terminal.
