### ISSUE TITLE
can you add support to Hynix NVMe  (PC300 512GB)?

### ISSUE THREAD

**Issue by YaHue** [RehabMan/patch-nvme#14]
my ssd is Hynix NVMe (PC300 512GB) 
and I use [this post](http://www.insanelymac.com/forum/topic/319929-pikeralphas-nvme-patch-with-hynix-m2-ssds/?p=2354906),this not working.
can you add support to Hynix NVMe  (PC300 512GB)?

**Comment by YaHue** [comment]
I know how to solve
[there](https://github.com/darkhandz/XPS15-9550-Sierra/issues/48)

**Comment by RehabMan** [comment]
See "Special patches for LiteOn/Plextor/Hynix NVMe" in README.
