### ISSUE TITLE
Update preparation 

### ISSUE THREAD

**Issue by jannispl** [RehabMan/patch-nvme#15]
Hey, could you give some hints on how to prepare for macOS updates in the future? The way I did it now for 10.12.3 was:
- gather the original NVMe kext from an updated system
- patch it
- move it to some place on a bootable macOS installer
- started the update
- before booting for the first time, remove original NVMe kext using USB installer, place Hackr kext into clover efi 
- experience kernel panic on first boot
- boot into installed macOS using old 10.12.2 USB installer 
- experience reboot 
- boot into updated macOS normally

**Comment by RehabMan** [comment]
No need for any special sequence if you use the class-code spoof.
You can simply leave the HackrNVMeFamily in place during the update as it does not conflict with any IONVMeFamily (hence why you don't have to delete IONVMeFamily).
Then, at your leisure after the update, remove the old HackrNVMeFamily, generate a new HackrNVMeFamily, and install it.

If you're not using the class-code spoof, you're just causing your own pain...
