### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by dirkduellmann** [RehabMan/patch-nvme#16]
In README.md:

cd patch-nvme.git

should be 

cd patch-nvme

**Comment by RehabMan** [comment]
Wrong.  The README specifically places the git copy in patch-nvme.git:

git clone https://github.com/RehabMan/patch-nvme.git patch-nvme.git

**Comment by dirkduellmann** [comment]
Oops - indeed, just a bit unconventional...  Thanks for the brilliant patch tool!

**Comment by RehabMan** [comment]
I like to use .git extensions on git working copies, so I remember they are connected to a git repo.
