### ISSUE TITLE
samsung sm 951 error

### ISSUE THREAD

**Issue by Mattosx** [RehabMan/patch-nvme#2]
Hello,my osx version is 10.11.5.i use samsung sm 951 for my data disk through the NVMeGeneric.kext.So i remove the NVMeGeneric.kext and run ./patch-nvme 10_11_5,a lot of error occur.Thank you.
![2016-07-20_06:51:12.jpg](https://oac4vcc05.qnssl.com/2016-07-20_06:51:12.jpg)

**Comment by RehabMan** [comment]
Read the README and follow carefully.
Your image is broken.
