### ISSUE TITLE
Script broken

### ISSUE THREAD

**Issue by dekefake** [RehabMan/patch-nvme#23]
patch_nvme - line 62 : cp: invalid option -- 'X'
I removed the X and the script ran flawessely - patching 10.12.4 kext

---   cp -RX $unpatched $patched
+++ cp -R $unpatched $patched

**Comment by RehabMan** [comment]
Nothing wrong with the script.
the -X option is valid with the 'cp' provided by Apple.
You must have installed a different version of 'cp' than the one provided by Apple.
