### ISSUE TITLE
Working, but not with spoof

### ISSUE THREAD

**Issue by yllapilate** [RehabMan/patch-nvme#28]
I believe I got each step right with my effort and reading your instructions multiple times, but can't seem to get the spoof to work properly. Works without spoof and by removing the original driver, but not otherwise. Could you please take a glance [**at this**](https://www.tonymacx86.com/threads/storks-myhero-build-asus-rog-maximus-viii-hero-i7-6700k-gtx-980.197284/page-114#post-1526330) and see if anything stands out?

**Comment by RehabMan** [comment]
Reply with "Problem Reporting" files in the patch-nvme/spoof guide thread.
