### ISSUE TITLE
My NVME SSD shows as external rather than internal

### ISSUE THREAD

**Issue by TomHeaven** [RehabMan/patch-nvme#30]
Hi, the patch works almost perfect for my NVME SSD except that the device is detected as ``external`` rather than ``internal``.  As a result, the partitions of the SSD will appear in the desktop of my home directory. 

I wonder if there is a patch for this, thanks!

**Comment by RehabMan** [comment]
This is covered/fixed in the guide linked from the README:
https://www.tonymacx86.com/threads/guide-hackrnvmefamily-co-existence-with-ionvmefamily-using-class-code-spoof.210316/
