### ISSUE TITLE
Create kext for different macOS version

### ISSUE THREAD

**Issue by yspreen** [RehabMan/patch-nvme#38]
I'm trying to build my first hackintosh and do not have any apple hardware. I use a macOS 10.12.0 vm to create the boot-media. But the App Store will only download 10.12.6. I only have one disk, and its the NVMe that doesnt show up.

How can I patch the 12.6 files on a 12.0 system? Can I maybe use the recovery mode of the 12.6 system? Is it capable of running the scripts?

**Comment by yspreen** [comment]
On a similar node, How do I edit SLE if I cannot even install? is there a SLE in the installer?

**Comment by yspreen** [comment]
Okay, it just doesnt get better. I upgraded my VM to 12.6 now, and was able to create the patched file. I use the spoof option. Copying it to the Kext/10.12 or Kext/Other dirs of clover (I tried both) the kernel panicks. What's wrong?
![img](https://i.imgur.com/UUGEAxl.png)

**Comment by yspreen** [comment]
Answered [here](https://www.tonymacx86.com/threads/unable-to-install-on-nvme.248102/)

**Comment by RehabMan** [comment]
See spoof guide linked from README:
https://www.tonymacx86.com/threads/guide-hackrnvmefamily-co-existence-with-ionvmefamily-using-class-code-spoof.210316/
