### ISSUE TITLE
Plextor m9PeY and Mojave

### ISSUE THREAD

**Issue by nofoxgit** [RehabMan/patch-nvme#47]
I have Plextor 512m9PeY and MacOS 10.14 Mojave installed (fresh install) on other SSD (Samsung 970EVO M.2). Everything working pretty well but Plextor SSD not.. I want it only for sotrage not for my system. Its visible in Windows but not visible in BIOS (MSI Z370 SLI PLUS motherboard). Are there any way to make this Plextor drive visible and usable in under MacOS ?? 

Thanks for any help.

**Comment by RehabMan** [comment]
Look at config_patches.plist for a patch that may be applicable.
