### ISSUE TITLE
Poor 10.12.0 Performance

### ISSUE THREAD

**Issue by maleorderbride** [RehabMan/patch-nvme#5]
I have installed the 10.12.0 version of HackrNVMeFamily (I had to put in SLE to get it to load), but I have very slow NVMe performance with my Intel P3605 PCI-e SSD.

I am getting 645/640 write/read with AJA System Test versus north of 1600/1600 under 10.11.6 with GenericNVMeFamily.kext.

Any ideas? What files can I provide?

**Comment by RehabMan** [comment]
No idea.  The patches are done based on Pike's work.
You probably should have purchased a Samsung drive.

**Comment by hugheba** [comment]
I'm in the same situation but I am using a Samsung  950 Pro M2 drive only getting about 40 read/write.

I was using the NVMeGeneric.kext getting around 1400 read/write in El Capitan. 

Will follow this thread to see if anyone has any ideas.

**Comment by NickWoodhams** [comment]
@hugheba Do you still have any other NVMe kexts installed? Run "sudo kextstat | grep NVM" in terminal and check the output. I am running 10.12.0 on a raid 0 stripe of 2 950 Pros and getting solid read/write speeds.. even though there is an error spamming my console. 
![screenshot 2016-09-28 08 28 49](https://cloud.githubusercontent.com/assets/1296347/18913507/3243987e-8556-11e6-8c6c-ef1d8a6f2386.png)

**Comment by hugheba** [comment]
@NickWoodhams I've made sure to remove the NVMeGeneric.kext I was using for El Capitan cause Sierra would kernel panic with it.

% sudo kextstat | grep NVM
Password:
   56    0 0xffffff7f81d4d000 0x38000    0x38000    com.apple.iokit.IONVMeFamily (2.1.0) B460E2CE-D16E-3C0F-B41F-0E2A84FEB291 <42 27 24 23 12 7 6 5 4 3 1>

I do notice something strange which is that I now have a new virtual drive /dev/disk4. It looks to maybe be part of the new APFS.

Disk Utility lists /dev/disk4 as the mount for "Macintosh HD" which is the drive that is performing slowly, both in Aja and Black Magick Disk Speed Test.

![2016-09-28_19-50-31](https://cloud.githubusercontent.com/assets/1189434/18936484/aee780a2-85b5-11e6-8bb5-8507c843a2f3.png)

![2016-09-28_19-56-12](https://cloud.githubusercontent.com/assets/1189434/18936486/b37478fa-85b5-11e6-95eb-221d32080874.png)

![2016-09-28_19-53-02](https://cloud.githubusercontent.com/assets/1189434/18936487/b715abf0-85b5-11e6-9ea0-bdd420a0ad0f.png)

**Comment by RehabMan** [comment]
If you're following the README here, it would be listed as com.apple.hack.HackrNVMeFamily, not com.apple.iokit.IONVMeFamily

Clearly you didn't follow the README.
